# This is the main configuration file of the sampler
# Any parameters should be defined here.

# Parameters of the measure task
device_read_rate: 0.25

# Maximum time allowed to read devicestatus
device_timeout:
  seconds: 10
  times: 10

measure: # Parameters of the measure task
  timeout: 1800
  # base sample volume, 50ml are added for the CoWS
  # and for the sample robot 2 x flushvol + bottlesize
  samplevol: 25
  throughflow:
    flushtime: 10

devices:
  # List of devices, if you want to disable some devices, comment it out
  valvesystem:
    module: trailer.devices.fakedevice
    host: wago
    port: 502
    # Execute the method / comethod after creation
    on_setup_complete: reset
    on_create: start_ysi

  ysi600r:
    module: trailer.devices.fakedevice
    # serial port of device
    port: /dev/trailerYSI
    # Measure time to make averages of result
    integrationtime: 20
    # Report error if no result was sampled for time in seconds
    timeout: 10

  fakedev:
    module: trailer.devices.fakedevice
    a: 1.0
    b: 2.0
    c: 3.0

mirror_db:
    url: http://10.8.0.1:10081/update/receive

