
# Coordinator for CoWS (Continuous Water Samplers) using the HIDS analyzer

[UserEditableParams]
num_disp_params = 0
0 = "readytime","Time in seconds needed to finish sample","1080"
1 = "switchtime","Time in seconds before sample time, when the source may be switched already:","180"
2 = "averaging_Time","Time Duration for Averaging and Reporting Isotope Data in Seconds","120"
3 = "warmup_Time","Warmup delay in min, 0 for no warmup, 15 min for warmup","15"
4 = "warmup_Source","Inlet for Water Source for System Warmup (15 Minutes): Select 1-4","4"
5 = "total_duration","Total length of time for operation in Minutes: Select 0 for indefinite","0"
6 = "verbose","Frequent output Y/N","Y"

[Mode]
inject_mode = automatic

[Archiver]
archiveGroupName = Coordinator

[Files]
output = "c:/IsotopeData/IsoWater_CoWS"
log = "c:/IsotopeData/Log/Log_CoWS"

[Output]
line_Num                     = "Line",%20d
startLocal                   = "Time", %22s
time                         = "Time_since_start", %15s
sample_Inlet_Port            = "Inlet_Port", %10i
sample_name                  = "Sample", %15s
Delta_18_16                  = "d(18_16)",%20.3f
Delta_D_H                    = "d(D_H)",%20.3f
H2O                          = "Water_ppm", %20.3f
water_Temperature            = "Water_Temp_C", %50s
ePTFE_Temperature            = "Membrane_Temp_C", %20s
trans_Temperature            = "Transfer_Line_Temp", %20s
air_Temperature              = "Air_Temp", %20s        
air_FlowRate                 = "Air_Flow_Rate_sccm", %20s
PID_loops_locked             = "PID_loops_locked", %5s
CH4                          = "Methane_ppm", %20.3f
baseline_shift               = "baseline_shift",%14.3f
baseline_curvature           = "baseline_curvature",%14.3f
slope_shift                  = "slope_shift",%14.3f
residuals                    = "residuals", %14.3f

[Setup]
initial=StateSetupCoWS
final=StateDone
error=StateError


[StateSetupCoWS]
action = """
logFunc("Loading modules...\n")
import sys
if 'splitsymbol' not in globals():
    sys.path.append("c:/python27/Lib/site-packages")

from ilrcws.cwscommunicator import CoWSChecker, CoWSCommunicator

logFunc("Searching COM ports for Continuous Water Sampler...\n")
CoWS = None
CoWSFound = False
for p in range(2,100):
    if CoWS:
        CoWS.close()
        CoWS = None
    try:
        CoWS = SerIntrf(p, timeout=250, xonxoff=0)
        sleep(3)
    except:
        continue
    try:
        logFunc("Talking to COM%d...\n"%(p+1))
        CoWS.sendString("C7")
        status = CoWS.getLine()
        logFunc(status)
        if "CoWS" in status:
            logFunc("CoWS found at COM%d...\n"%(p+1))
            CoWSFound = True
            break
    except:
        pass
        

if not CoWSFound:
    logFunc("Continuous Water Sampler not found.\n")
    if CoWS:
        CoWS.close()
        CoWS = None
    GUI.popWarning("Continuous Water Sampler not found", "CoWS not found")
    raise Exception("CoWS not found")
else:
    # Turn on Temperature Control
    CoWS.sendString("T1")

    # Turn on Air Flow Control
    CoWS.sendString("A1")
    # Turn on Water Pump
    CoWS.sendString("W1")

NEXT = "StateSetup"


"""
[StateSetup]
action = """

# duration_Calibration = float(editParamDict["duration_Calibration"])*60.0
averaging_Time = float(editParamDict["averaging_Time"])
warmup_Time = int(editParamDict["warmup_Time"])
warmup_Source = int(editParamDict["warmup_Source"])
total_duration = float(editParamDict["total_duration"])*60.0
concNameList = ["Delta_18_16", "Delta_D_H", "H2O", "CH4", "baseline_shift", "baseline_curvature", "slope_shift", "residuals"]


setMeasBuffer("analyze_iH2O7200", concNameList, 2*averaging_Time)
clearMeasBuffer()

logFunc("Create checker\n")
checker = CoWSChecker(editParamDict,concNameList)
logFunc("Create communicator\n")
communicator = CoWSCommunicator(checker)
communicator.start()
try:
    import CoordinatorScripts
    INSTMGR = CoordinatorScripts.INSTMGR
    logFunc("Using real instrument status...\n")
except:
    logFunc("Using fake instrument status...\n")
    INSTMGR = InstMgrFake()


data_Buffer = {}
data_Buffer_Int = {}
calculated_Results = {}

line_Count = 0
currentport = 0


def str_time(t=None, postfix=''):
    # Returns a string representation of the utc time.
    # t is a float as returned by time.time(). If t is None, time.time() is called
    return time.strftime('%Y/%m/%d %H:%M:%S', time.gmtime(t or time.time())) + postfix

def log_time(msg, t=None):
    logFunc('%s: %s\n' % (str_time(t), msg))

def prepare_CoWS_Data():
    # Sends the status string to the CoWS but does NOT wait for an answer (approx. 4s)
    # returns the actual time
    try:
        CoWS.sendString("C8")
    except:
        log_time('Could not send C8 to CoWS!')
    return time.time()

def get_CoWS_Data():
    # Reads the status from the CoWS, it is mandatory that prepare_CoWS_Data has been called before
    try:
        status = CoWS.getLine()
        CoWS_Status = status.split()
    except:
        logFunc('CoWS had no data!')
    return CoWS_Status

def report_Data(results, sample=''):
    calculated_Results["H2O"] = results["H2O"]
    calculated_Results["Delta_D_H"] = results["Delta_D_H"]
    calculated_Results["Delta_18_16"] = results["Delta_18_16"]
    calculated_Results["CH4"] = results["CH4"]
    calculated_Results["line_Num"] = line_Count
    calculated_Results["time"] = round(((time.time()-start_Time_from_begining)/60.0),2)
    calculated_Results["startLocal"] = results['date']
    calculated_Results["baseline_shift"] = results["baseline_shift"]
    calculated_Results["baseline_curvature"] = results["baseline_curvature"]
    calculated_Results["slope_shift"] = results["slope_shift"]
    calculated_Results["residuals"] = results["residuals"]

    calculated_Results["water_Temperature"] = results.get('Water_T', 0.0)
    calculated_Results["ePTFE_Temperature"] = results.get('ePTFE_T', 0.0)
    calculated_Results["trans_Temperature"] = results.get('trans_T', 0.0)
    calculated_Results["air_Temperature"] = results.get('trans_T', 0.0)
    calculated_Results["air_FlowRate"] = results.get('air_Flow', 0.0)
    calculated_Results["PID_loops_locked"] = results.get('PID_loops_locked', 0.0)

    calculated_Results["sample_Inlet_Port"] = currentport
    calculated_Results["sample_name"] = sample
    fileDataFunc(calculated_Results)

    return calculated_Results

start_Time_from_begining = time.time()
if warmup_Time > 0:
    NEXT = "StateWarmUp"
else:
    NEXT = "StateSample"


"""
[StateWarmUp]
action = """
currentport = int(warmup_Source)

Position = "P" + str(warmup_Source)
log_time("CoWS inlet set to Position %d..." % currentport)
CoWS.sendString(Position)
start_Time = start_Time_from_begining
loop_time = time.time()
log_time("start time " )
# Send status request to CoWS, retrieve later
cows_time = prepare_CoWS_Data()
# Get a first data set
results = measGetBufferFirst()
while not results:
    sleep(0.2)
    results = measGetBufferFirst()
log_time("got result: %0.1f ppm" % results['H2O'])
# retrieve CoWS data
cows_data = get_CoWS_Data()
# prepare new CoWS data
cows_time = prepare_CoWS_Data()

if checker.verbose():
    log_time('New CoWS Data, %d values' % len(cows_data))

checker.setstatus(warmup_Source, INSTMGR.INSTMGR_GetStatusRpc())
line_Count += 1
report_Data(results)
log_time("Start WARMUP for %s min" % warmup_Time)

start_warmup_time = time.time()

while (time.time() - start_warmup_time) < warmup_Time * 60:
    loop_time = time.time()
    results = measGetBufferFirst()
    while not results:
        sleep(0.2)
        results = measGetBufferFirst()
    # Read CoWS only every 5sec
    if time.time() - cows_time >= 5.0:
        cows_data = get_CoWS_Data()
        cows_time = prepare_CoWS_Data()
        if checker.verbose():
            log_time('new CoWS data, %d values, %0.0fs remain for warm up'
                    % (len(cows_data), warmup_Time*60 - (time.time()-start_warmup_time)))

    # Update results with CoWS data
    results.update(dict((k, float(v)) for k, v in
                        zip('Water_T ePTFE_T trans_T air_T air_Flow PID_loops_locked'.split(),
                            cows_data)))
    results['warmup'] = warmup_Time * 60 - (time.time() - start_warmup_time)
    checker.appendvalues(time.time(), results)
    line_Count += 1

    report_Data(results, 'WarmUp')
    if checker.stop():
        break
# Read remaining data from CoWS
cows_data = get_CoWS_Data()
if checker.stop():
    NEXT = "StatePause"
else:
    NEXT = "StateSample"


"""
[StateSample]
action = """
nextport = 0
if 'cows_data' not in globals():
    cows_data = [0.0] * 6
cows_time = prepare_CoWS_Data()
while (not total_duration) or (time.time()-start_Time_from_begining)<total_duration:
    # checker.nextport evaluates the stored results so far,
    # and decides which port to use next
    start_Time = time.time()
    checker.setstatus(currentport, INSTMGR.INSTMGR_GetStatusRpc())
    nextport, sample = checker.nextport(currentport, log_time)
    if nextport != currentport: # Next port gave a new port to sample
        cows_data = get_CoWS_Data()
        currentport=nextport
        log_time("%s: CoWS inlet set to Position %r..." % (time.ctime(),currentport))


        # Change valco position
        Position = "P{}".format(currentport)
        CoWS.sendString(Position)
        cows_time = prepare_CoWS_Data()
    elif nextport == 0:
        # Clear CoWS buffer
        log_time('leave StateSample')
        break
    else:
        pass
    results = measGetBufferFirst()
    while not results:
        sleep(0.2)
        results = measGetBufferFirst()

    # Read CoWS only every 5sec
    if time.time() - cows_time >= 5.0:
        cows_data = get_CoWS_Data()
        cows_time = prepare_CoWS_Data()
        if checker.verbose():
            log_time('new CoWS data, %d values' % len(cows_data))
    results.update(dict((k, float(v)) for k, v in
                        zip('Water_T ePTFE_T trans_T air_T air_Flow PID_loops_locked'.split(),
                            cows_data)))
    results['warmup'] = 0
    checker.appendvalues(time.time(), results)
    
    for variable in results:
        data_Buffer.setdefault(variable, []).append(results[variable])

    line_Count += 1
    report_Data(results, sample)

# read remaining data from serial buffer
cows_data = get_CoWS_Data()
NEXT = "StatePause"


"""


[StatePause]
action="""
CoWS.sendString("T0")
CoWS.sendString("W0")
CoWS.sendString("A0")
log_time('CoWS went to pause mode...')
while True:
    time.sleep(1.0)
    if checker.resume():
        log_time('CoWS resumes, 15min for warm up')
        NEXT='StateSetupCoWS'
        break
    elif checker.stop():
        log_time('StatePause: Stopping CoWS')
        NEXT='StateDone'
        break


"""
[StateDone]
action="""
CoWS.sendString("T0")
CoWS.sendString("W0")
CoWS.sendString("A0")
log_time("Done!")
NEXT=""

    
"""


[StateError]
action="""
log_time("Error %s in state %s" % (ERROR_MSG,ERROR_STATE))
NEXT = "StateDone"
"""
