#!/bin/sh
echo "Shut down the sampler..."
curl --data '' "http://localhost:10080/shutdown_server" && sleep 5
show
echo "Shut down logger..."
python3 /home/trailer/trailer/test/jsonsocket.py stop && sleep 5
show
